# -*- coding: utf-8 -*-
"""ScriptByUniversites1 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mM6OU1ZlBujWPuvE1XrJF7cz21GrydrP
"""

import pandas as pd


chemin_fichier = r'C:\\Users\\sadou\\Downloads\\archive-1\\student_profiles.jsonl'

df = pd.read_json(chemin_fichier, lines=True)

df["Université"] = "Université de " + df["State/Province"]

nombre_etudiants_par_universite = df.groupby('Université').size().reset_index(name='NombreEtudiants')

chemin_fichier_modifié = r'C:\\Users\\sadou\\Downloads\\archive-1\\student_profiles_modified.jsonl'
nombre_etudiants_par_universite.to_json(chemin_fichier_modifié, orient="records", lines=True, force_ascii=False)