# -*- coding: utf-8 -*-
"""TauxAbondon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z9xYqpsnJmupn2_-qmxAxkd5ZIwfScCn
"""

import pandas as pd
import json
import numpy as np

chemin_fichier = r'C:\\Users\\sadou\\Downloads\\archive-1\\student_profiles.jsonl'
df = pd.read_json(chemin_fichier, lines=True)

grouped = df.groupby(['Major', 'Year']).size().unstack(fill_value=0)

if 'Junior' not in grouped.columns:
    grouped['Junior'] = 0
if 'Senior' not in grouped.columns:
    grouped['Senior'] = 0
grouped['Taux(Abandon/Engagement) (%)'] = ((grouped['Senior'] - grouped['Junior']) / grouped['Junior'].replace(0, np.nan)) * 100

grouped['Taux(Abandon/Engagement) (%)'].replace([np.inf, -np.inf], np.nan, inplace=True)

result_json = grouped[['Junior', 'Senior', 'Taux(Abandon/Engagement) (%)']].reset_index().to_json(orient='records')

chemin_fichier_sortie = r'C:\\Users\\sadou\\Downloads\\archive-1\\student_profiles_taux_abandon_engagement.json'

with open(chemin_fichier_sortie, 'w', encoding='utf-8') as f:
    f.write(result_json)